node() {
    checkout scm
    if (env.BRANCH_NAME =~ 'develop') {
        echo 'loading Jenkinsfile-develop'
        load 'Jenkinsfile-develop'
    } else if (env.BRANCH_NAME =~ 'master') {
            echo 'loading Jenkinsfile-master'
            load 'Jenkinsfile-master'
    }
}